on:
  push:
    branches: master

name: Pkgdown

jobs:
  pkgdown:
    env:
      CI: true
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: |
          install.packages("remotes", repos = "https://ftp.fau.de/cran/")
          remotes::install_deps(dependencies = TRUE, repos = "https://ftp.fau.de/cran/")
          remotes::install_github("r-lib/pkgdown")
        shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL .
      - name: Deploy package
        run: |
          pkgdown::deploy_to_branch()
        shell: Rscript {0}
